In [25]:
from tensorflow.keras.layers import LayerNormalization
import numpy as np

In [26]:
arr = np.random.rand(2, 3, 3, 1) * 100
arr

array([[[[49.44940413],
         [32.84864438],
         [94.27106281]],

        [[67.82241501],
         [55.95169523],
         [85.90151619]],

        [[72.95117523],
         [14.73856976],
         [28.03875385]]],


       [[[70.82659542],
         [75.81976801],
         [ 9.26653031]],

        [[90.82011622],
         [68.48625856],
         [68.23659441]],

        [[73.88187488],
         [66.45510233],
         [ 9.94101007]]]])

In [28]:
LayerNormalization(axis=1)(arr)

<tf.Tensor: shape=(2, 3, 3, 1), dtype=float32, numpy=
array([[[[-1.38342   ],
         [-0.0986774 ],
         [ 0.84443593]],

        [[ 0.43755198],
         [ 1.2710965 ],
         [ 0.5602255 ]],

        [[ 0.94586897],
         [-1.1724188 ],
         [-1.4046609 ]]],


       [[[-0.8736696 ],
         [ 1.3837891 ],
         [-0.7192719 ]],

        [[ 1.3999062 ],
         [-0.43941116],
         [ 1.4141425 ]],

        [[-0.52623653],
         [-0.9443817 ],
         [-0.6948706 ]]]], dtype=float32)>